project:
  type: website

website:
  title: "dep-wq-fine-scale-analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    code-fold: true
    message: flase
    warning: false



